### ISSUE TITLE
toString?

### ISSUE THREAD

**Issue by markwylde** [KoryNunn/presh#23]
What sort of witchcraft is `toString`?

It seems to be "hardcoded" into the scope, and we can't override it?

Is this intentional?

**Comment by markwylde** [comment]
Presh(`toString(1)`, { toString: (a) => String(1) }

**Comment by KoryNunn** [comment]
Fixed in https://github.com/KoryNunn/presh/commit/fb2b560a8b79401d202a5736109799788d526994
